language: python
dist: xenial
python:
  - 2.7
  - 3.7
  - 3.8
install: pip install tox-travis coveralls
script: tox
after_success:
  - coverage combine
  - coveralls
cache:
  pip: true

notifications:
  webhooks:
    secure: UNCeHvnzS4le/n44WK8mP1EN/psPlNEj//Q2NtoTZuP8AUle7xXAFjUvFOGrByC1170j79gD5kSAb4jrxeamwKwvB/MLYUog9wh+JAMx8J2seBoQr42T4tDvURHAqNaiSqUX97RgfPaE9cJdaQ43uNW0ug+VZG36+Op7sOvhv/kqi4H1qqd0kZvfSAtb+d4drkOFtE9zDNrcrz4l477h69jZvIHK0qeAPbAvbF4TNj2FNMnbV2crahXdVgBShJ1GNyfrwsX5jcgqzTzkw5WWehyFKdz3qOJ+3ra6tY2boxbIZsMnXBhurjIDSnAwbXkldXMTZQKfKcdKINFvULlScYi3xcQ9fbs73iJ8f2kMh6AAf2o25cT8JlHZi1kNYE8DdQN58rwgWZAfYw5kBuZhY1LW/Vycdc8ZyObSSzo5/39gYMdFYdO1bWK/z0CFZyHY5ELmH+S0jmB6Mb+SDgOGhELbeEf0MPT86h/P3hiEA3sW09cfE1dJc3Wp/LcYl2A44v1boufzx75hM8Sxbbj4lEU+S99eeLAHeq3dxtULDQOzZRhCMKbX2uR+Bjwn1GTfQCct1h0s88Dik+2QV0RKXKm9ms8RINalh9zTJ5lw5LrqpfbqR4MvgnD84jjEcdrbJUg+vNW9h8NwHPkVxy3cW7WE9cFEXgGH5AgKNV39ncM=
